#!/bin/bash
# Only change these 2 paths if you want to compile a kernel on your own
export ARM_EABI=/home/vork/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-
export BUILD_DIR=~/Dropbox/Public

kernelconfig=`cat Tools/misc/config`
if grep -q "GSM" "Tools/misc/config"; then
	GC=""
else
	GC="-CDMA"
fi
if grep -q "Stock" "Tools/misc/config"; then
	CAM=""
else
	CAM="-720p"
fi

clear

echo "----------------------------------------"
echo "Building for:" $kernelconfig
echo "1 - SVS CFS 925mv@1289Mhz"
echo ""
echo "2 - SVS CFS ADVANCED (vdd sysfs interface)"
echo ""
echo "10 - GSM/CDMA and cam toggle"
echo "0 - Exit"
echo "----------------------------------------"
read BUILD
case $BUILD in
        1)
            	echo "Building SVS 925mv CFS"
                make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelSVS_bravo_defconfig
		signed_file=vorkKernel$GC$CAM-SVS-CFS.zip
                . compile.sh
                ;;
        2)
            	echo "Building SVS CFS with vdd sysfs interface"
                make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelSVSADV_bravo_defconfig
		signed_file=vorkKernel$GC$CAM-SVS-CFS-ADV.zip
                . compile.sh
                ;;
	10)
		clear
		echo "----------------------------------------"
		echo "Currently building for a" $kernelconfig "Rom"		
		echo "1 - Network"
		echo "2 - Cam"
		echo "3 - Exit"
		echo "----------------------------------------"
		read TOGGLE
		case $TOGGLE in
			1)
				if [ "$GC" == "" ]; then
					sed -i 's/CONFIG_MACH_BRAVO=y/# CONFIG_MACH_BRAVO is not set/g' arch/arm/configs/vorkKernel*
    					sed -i 's/# CONFIG_MACH_BRAVOC is not set/CONFIG_MACH_BRAVOC=y/g' arch/arm/configs/vorkKernel*
					sed -i 's/GSM/CDMA/g' Tools/misc/config
				else
					sed -i 's/CONFIG_MACH_BRAVOC=y/# CONFIG_MACH_BRAVOC is not set/g' arch/arm/configs/vorkKernel*
    					sed -i 's/# CONFIG_MACH_BRAVO is not set/CONFIG_MACH_BRAVO=y/g' arch/arm/configs/vorkKernel* 
					sed -i 's/CDMA/GSM/g' Tools/misc/config
				fi
				kernelconfig=`cat Tools/misc/config`
				echo "Now building for a" $kernelconfig "Rom"
				. build
				;;
			2)
				if [ "$CAM" == "" ]; then
					cp Tools/misc/720p.patch 720p.patch
					patch -p1 -s -f <720p.patch
					rm 720p.patch
					sed -i 's/Stock/720p/g' Tools/misc/config
				else
					cp Tools/misc/stockcam.patch stockcam.patch
					patch -p1 -s -f <stockcam.patch
					rm stockcam.patch
					sed -i 's/720p/Stock/g' Tools/misc/config
				fi
				kernelconfig=`cat Tools/misc/config`
				echo "Now building for a" $kernelconfig "Rom"
				. build
				;;
			3)
				. build
				;;
			10)
				NOW=$(date +"%d%m%y")
				sed -i 's/TESTVR/'$NOW'/g' arch/arm/configs/vorkKernel*
				;;
			11)
				sed -i 's/-vorkKernel-.*/-vorkKernel-TESTVR/g' arch/arm/configs/vorkKernel*
				;;
			*) echo "Error";;
		esac
		;;
	0) clear ;;
        *) echo "Error";;
esac
