#!/bin/bash
# Only change these 2 paths if you want to compile a kernel on your own
export ARM_EABI=/home/vork/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-
export BUILD_DIR=~/Dropbox/Public

kernelconfig=`cat Tools/misc/config`
if grep -q "GSM" "Tools/misc/config"; then
	GC=""
else
	GC="-CDMA"
fi
if grep -q "Stock" "Tools/misc/config"; then
	CAM=""
else
	CAM="-720p"
fi

clear

echo "----------------------------------------"
echo "Building for:" $kernelconfig
echo "1 - HAVS 875mv - BFS"
echo "2 - HAVS 900mv - BFS"
echo "3 - HAVS 925mv - BFS"
echo
echo "4 - HAVS 875mv - CFS"
echo "5 - HAVS 900mv - CFS"
echo "6 - HAVS 925mv - CFS"
echo
echo "7 - SVS 975mv (stock) - BFS"
echo "8 - SVS 925mv - BFS"
echo "9 - SVS 900mv - BFS"
echo
echo "10 - SVS 975mv (stock) - CFS"
echo "11 - SVS 925mv - CFS"
echo "12 - SVS 900mv - CFS"
echo
echo "13 - all - not implemented yet"
echo "14 - Exit"
echo "0 - GSM/CDMA and cam toggle"
echo "----------------------------------------"
read BUILD
case $BUILD in
        1)
            	echo "Building HAVS 875mv BFS"
                make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernel_bravo_defconfig
                old_voltage=`cat .config | grep CONFIG_AVS_...=y | cut -c12-14`
                sed -i 's/CONFIG_AVS_'$old_voltage'=y/# CONFIG_AVS_'$old_voltage' is not set/g' .config
                sed -i 's/# CONFIG_AVS_875 is not set/CONFIG_AVS_875=y/g' .config
                . compile.sh
                ;;
        2)
            	echo "Building HAVS 900mv BFS"
                make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernel_bravo_defconfig
                old_voltage=`cat .config | grep CONFIG_AVS_...=y | cut -c12-14`
                sed -i 's/CONFIG_AVS_'$old_voltage'=y/# CONFIG_AVS_'$old_voltage' is not set/g' .config
                sed -i 's/# CONFIG_AVS_900 is not set/CONFIG_AVS_900=y/g' .config
                . compile.sh
                ;;
        3)
            	echo "Building HAVS 925mv BFS"
                make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernel_bravo_defconfig
                . compile.sh
                ;;
        4) 
            	echo "Building HAVS 875mv CFS"
        	make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelCFS_bravo_defconfig
                old_voltage=`cat .config | grep CONFIG_AVS_...=y | cut -c12-14`
                sed -i 's/CONFIG_AVS_'$old_voltage'=y/# CONFIG_AVS_'$old_voltage' is not set/g' .config
                sed -i 's/# CONFIG_AVS_875 is not set/CONFIG_AVS_875=y/g' .config
        	. compile.sh
                ;;  
        5) 
            	echo "Building HAVS 900mv CFS"
        	make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelCFS_bravo_defconfig
                old_voltage=`cat .config | grep CONFIG_AVS_...=y | cut -c12-14`
                sed -i 's/CONFIG_AVS_'$old_voltage'=y/# CONFIG_AVS_'$old_voltage' is not set/g' .config
                sed -i 's/# CONFIG_AVS_900 is not set/CONFIG_AVS_900=y/g' .config
        	. compile.sh
                ;; 
        6) 
            	echo "Building HAVS 925mv CFS"
        	make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelCFS_bravo_defconfig
        	. compile.sh
                ;; 
        7)
            	echo "Building SVS 975mv BFS"
                make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelSVS_bravo_defconfig
                . compile.sh
                ;;
        8)
            	echo "Building SVS 925mv BFS"
                make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelSVS_bravo_defconfig
                . compile.sh
		old_voltage=`cat .config | grep CONFIG_SVS_...=y | cut -c12-14`
                sed -i 's/CONFIG_SVS_'$old_voltage'=y/# CONFIG_SVS_'$old_voltage' is not set/g' .config
                sed -i 's/# CONFIG_SVS_925 is not set/CONFIG_SVS_925=y/g' .config
                ;;
        9)
            	echo "Building SVS 900mv BFS"
                make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelSVS_bravo_defconfig
                . compile.sh
		old_voltage=`cat .config | grep CONFIG_SVS_...=y | cut -c12-14`
                sed -i 's/CONFIG_SVS_'$old_voltage'=y/# CONFIG_SVS_'$old_voltage' is not set/g' .config
                sed -i 's/# CONFIG_SVS_900 is not set/CONFIG_SVS_900=y/g' .config
                ;;
        10) 
            	echo "Building SVS 975mv CFS"
        	make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelCFSSVS_bravo_defconfig
        	. compile.sh
                ;;
        11) 
            	echo "Building SVS 925mv CFS"
        	make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelCFSSVS_bravo_defconfig
        	. compile.sh
		old_voltage=`cat .config | grep CONFIG_SVS_...=y | cut -c12-14`
                sed -i 's/CONFIG_SVS_'$old_voltage'=y/# CONFIG_SVS_'$old_voltage' is not set/g' .config
                sed -i 's/# CONFIG_SVS_925 is not set/CONFIG_SVS_925=y/g' .config
                ;;
       	12) 
            	echo "Building SVS 900mv CFS"
        	make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelCFSSVS_bravo_defconfig
        	. compile.sh
		old_voltage=`cat .config | grep CONFIG_SVS_...=y | cut -c12-14`
                sed -i 's/CONFIG_SVS_'$old_voltage'=y/# CONFIG_SVS_'$old_voltage' is not set/g' .config
                sed -i 's/# CONFIG_SVS_900 is not set/CONFIG_SVS_900=y/g' .config
                ;;
	0)
		clear
		echo "----------------------------------------"
		echo "Currently building for a" $kernelconfig "Rom"		
		echo "1 - Network"
		echo "2 - Cam"
		echo "3 - Exit"
		echo "----------------------------------------"
		read TOGGLE
		case $TOGGLE in
			1)
				if [ "$GC" == "" ]; then
					sed -i 's/CONFIG_MACH_BRAVO=y/# CONFIG_MACH_BRAVO is not set/g' arch/arm/configs/vorkKernel*
    					sed -i 's/# CONFIG_MACH_BRAVOC is not set/CONFIG_MACH_BRAVOC=y/g' arch/arm/configs/vorkKernel*
					sed -i 's/GSM/CDMA/g' Tools/misc/config
				else
					sed -i 's/CONFIG_MACH_BRAVOC=y/# CONFIG_MACH_BRAVOC is not set/g' arch/arm/configs/vorkKernel*
    					sed -i 's/# CONFIG_MACH_BRAVO is not set/CONFIG_MACH_BRAVO=y/g' arch/arm/configs/vorkKernel* 
					sed -i 's/CDMA/GSM/g' Tools/misc/config
				fi
				kernelconfig=`cat Tools/misc/config`
				echo "Now building for a" $kernelconfig "Rom"
				. build
				;;
			2)
				if [ "$CAM" == "" ]; then
					cp Tools/misc/720p.patch 720p.patch
					patch -p1 -s -f <720p.patch
					rm 720p.patch
					sed -i 's/Stock/720p/g' Tools/misc/config
				else
					cp Tools/misc/stockcam.patch stockcam.patch
					patch -p1 -s -f <stockcam.patch
					rm stockcam.patch
					sed -i 's/720p/Stock/g' Tools/misc/config
				fi
				kernelconfig=`cat Tools/misc/config`
				echo "Now building for a" $kernelconfig "Rom"
				. build
				;;
			3)
				. build
				;;
			*) echo "Error";;
		esac
		;;
	14) clear ;;
        *) echo "Error";;
esac
