#!/bin/bash
# Only change these 2 paths if you want to compile a kernel on your own
export ARM_EABI=~/helios/install/bin/arm-eabi-
export BUILD_DIR=~/Dropbox/Public

clear

echo "----------------------------------------"
echo "Build:"
echo "1 - HAVS 875mv - BFS"
echo "2 - HAVS 900mv - BFS"
echo "3 - HAVS 925mv - BFS"
echo "4 - HAVS 875mv - CFS"
echo "5 - HAVS 900mv - CFS"
echo "6 - HAVS 925mv - CFS"
echo "7 - SVS - BFS"
echo "8 - SVS - CFS"
echo "9 - all - not implemented yet"
echo "----------------------------------------"
read BUILD
case $BUILD in
        1)
            	echo "Building HAVS 875mv BFS"
                make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernel_bravo_defconfig
                old_voltage=`cat .config | grep CONFIG_AVS_...=y | cut -c12-14`
                sed -i 's/CONFIG_AVS_'$old_voltage'=y/# CONFIG_AVS_'$old_voltage' is not set/g' .config
                sed -i 's/# CONFIG_AVS_875 is not set/CONFIG_AVS_875=y/g' .config
                . build.sh
                ;;
        2)
            	echo "Building HAVS 900mv BFS"
                make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernel_bravo_defconfig
                old_voltage=`cat .config | grep CONFIG_AVS_...=y | cut -c12-14`
                sed -i 's/CONFIG_AVS_'$old_voltage'=y/# CONFIG_AVS_'$old_voltage' is not set/g' .config
                sed -i 's/# CONFIG_AVS_900 is not set/CONFIG_AVS_900=y/g' .config
                . build.sh
                ;;
        3)
            	echo "Building HAVS 925mv BFS"
                make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernel_bravo_defconfig
                . build.sh
                ;;
        4) 
            	echo "Building HAVS 875mv CFS"
        	    make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelCFS_bravo_defconfig
                old_voltage=`cat .config | grep CONFIG_AVS_...=y | cut -c12-14`
                sed -i 's/CONFIG_AVS_'$old_voltage'=y/# CONFIG_AVS_'$old_voltage' is not set/g' .config
                sed -i 's/# CONFIG_AVS_875 is not set/CONFIG_AVS_875=y/g' .config
        	    . build.sh
                ;;  
        5) 
            	echo "Building HAVS 900mv CFS"
        	    make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelCFS_bravo_defconfig
                old_voltage=`cat .config | grep CONFIG_AVS_...=y | cut -c12-14`
                sed -i 's/CONFIG_AVS_'$old_voltage'=y/# CONFIG_AVS_'$old_voltage' is not set/g' .config
                sed -i 's/# CONFIG_AVS_900 is not set/CONFIG_AVS_900=y/g' .config
        	    . build.sh
                ;; 
        6) 
            	echo "Building HAVS 925mv CFS"
        	    make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelCFS_bravo_defconfig
        	    . build.sh
                ;; 
        7)
            	echo "Building SVS BFS"
                make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelSVS_bravo_defconfig
                . build.sh
                ;;
        8) 
            	echo "Building SVS CFS"
        	    make ARCH=arm CROSS_COMPILE=$ARM_EABI vorkKernelCFSSVS_bravo_defconfig
        	    . build.sh
                ;;
        *) echo "Error";;
esac
